name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        run: nix-shell -p cachix --run "cachix use pebble"
      - name: Install Pebble SDK
        run: echo "y" | nix-shell --run "pebble sdk install latest"
      - name: Build Pebble App
        run: nix-shell --run "python /home/runner/.pebble-sdk/SDKs/current/sdk-core/pebble/waf configure build --platform=basalt"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pebble-app
          path: build/*.pbw