name: Build with Lix

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Setup Nix environment for Lix and check version
        run: |
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          echo "PATH: $PATH"
          lix --version

      - name: List installed binaries
        run: |
          echo "Contents of /nix/var/nix/profiles/default/bin:"
          ls -l /nix/var/nix/profiles/default/bin
          echo "Contents of /home/runner/.nix-profile/bin:"
          ls -l /home/runner/.nix-profile/bin

      - name: Check for lix in PATH
        run: which lix || echo "lix not found"

        - name: Search for lix binary
        run: |
          echo "Searching for lix binary across the system..."
          find / -type f -name lix 2>/dev/null

      - name: Show Lix version
        run: lix --version

      # Replace the following step with your actual build command.
      # For example, if you have a flake that builds your Pebble app,
      # you might run:
      - name: Build project
        run: |
          # Adjust this to your build command (for example, nix build .#yourTarget)
          lix build .#yourTarget

      # Optional: Upload the build artifact.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-result
          path: result