name: Build with Pebble SDK

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Nix with necessary configuration
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            allow-unsafe-native-code-during-evaluation = true
            allow-import-from-derivation = true

      - name: Check Nix installation
        run: |
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          echo "Nix version:"
          nix --version

      # Build the Pebble project using the real SDK
      - name: Build Pebble project
        run: |
          echo "Building with Pebble SDK via Nix..."
          # Add unstable channel for newer packages
          nix-channel --add https://nixos.org/channels/nixos-unstable nixos
          nix-channel --update
          
          # Build the project with increased log output
          nix build --show-trace --verbose || {
            echo "Build failed, checking for errors..."
            find . -name "*.log" -exec cat {} \;
            exit 1
          }
          
          # Verify the build result
          echo "Checking build result:"
          ls -l result || echo "No result directory found"
          
          # If build succeeded, show contents
          if [ -L "result" ]; then
            echo "Build succeeded! Result directory contents:"
            ls -la result/
            ls -la result/bin/ || echo "No bin directory found"
          fi

      # Upload artifacts
      - name: Upload Pebble app artifact
        uses: actions/upload-artifact@v4
        with:
          name: pebble-app
          path: result/bin/*.pbw
          if-no-files-found: warn