name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Set Up Cachix
        uses: cachix/cachix-action@v14
        with:
          name: pebble
      - name: Build Pebble App
        run: nix build .#pebble-app
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pebble-app
          path: result/*.pbw