name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout your repository
      - uses: actions/checkout@v4

      # Step 2: Install Nix
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # Step 3: Configure Cachix for the pebble cache
      - name: Configure Cachix
        run: nix-shell -p cachix --run "cachix use pebble"

      # Step 4: Build the Pebble app with license prompt disabled
      - name: Build Pebble App
        env:
          PEBBLE_NO_LICENSE_PROMPT: "1"  # Skips the license prompt
        run: nix-shell --run "pebble build"

      # Step 5: Upload the built artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pebble-app
          path: build/*.pbw