name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: pebble
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Install Pebble SDK
        run: echo "y" | nix-shell --run "pebble sdk install latest"
      - name: Build Pebble App
        run: nix-shell --run "pebble build"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pebble-app
          path: build/*.pbw