name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - run: echo $PATH  # Debug step to check PATH
      - uses: cachix/cachix-action@v12
        with:
          name: pebble
      - run: nix-shell --run "pebble build"