name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Checks out your repository code
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
        # Installs Nix on the runner
      - run: nix-shell --run "pebble build"
        # Runs the build command in the Nix shell