name: Build Pebble App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository code
      - uses: actions/checkout@v2

      # Step 2: Install Nix with a compatible configuration
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      # Step 3: Install Cachix explicitly as a fallback
      - name: Install Cachix
        run: nix-env -iA cachix -f https://cachix.org/api/v1/install

      # Step 4: Debug PATH and Cachix installation
      - name: Debug PATH and Cachix
        run: |
          echo "PATH is: $PATH"
          which cachix || echo "cachix not found in PATH"
          cachix --version || echo "cachix command failed"

      # Step 5: Use the Pebble cache with Cachix
      - uses: cachix/cachix-action@v12
        with:
          name: pebble

      # Step 6: Build your Pebble app
      - run: nix-shell --run "pebble build"