name: Build with Lix

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@v1

      - name: Show Lix version
        run: lix --version

      # Replace the following step with your actual build command.
      # For example, if you have a flake that builds your Pebble app,
      # you might run:
      - name: Build project
        run: |
          # Adjust this to your build command (for example, nix build .#yourTarget)
          lix build .#yourTarget

      # Optional: Upload the build artifact.
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-result
          path: result